name = "ResumableFunctions"
uuid = "c5292f4c-5179-55e1-98c5-05642aab7184"
repo = "https://github.com/BenLauwens/ResumableFunctions.jl.git"
version = "0.5"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "0.4"
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
